theme: jekyll-theme-cayman
title: OOICloud

url: www.ooicloud.github.io

# Site settings
email: your-email@domain.com
description: "OOIcloud connects data from the Ocean Observatories Iniative to the computational capabilites of Azure Cloud Services."
